services:
  - type: web
    name: bot-worker-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python -m spacy download pt_core_news_sm"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PRODUCAO
        value: "true"
      - key: CONN_URL
        sync: false
      - key: WOLFRAM_APP_ID
        sync: false
      - key: GOOGLE_CX
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
